language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
install:
  - "pip install -r requirements.txt"
  - "pip install ."
script:
  - behave --tags=-@slow features/
  - py.test tests/
after_success:
  - true

# TODO:
# [ ] deploy package
