language: python
python:
  - "3.3"
  - "3.4"
install:
  - "pip install src/basepkg"
  - "pip install -r requirements.txt"
script:
  - py.test src/basepkg/tests
  - cd src/basepkg && behave --tags=-@slow features/
