language: python
python:
  - "3.3"
  - "3.4"
  - "pypy3"
install:
  - "pip install -r requirements.txt"
  - "cd src/basepkg && pip install ."
script:
  - behave --tags=-@slow features/
  - py.test tests/

#  - py.test src/basepkg/tests
#  - cd src/basepkg && behave --tags=-@slow features/
