language: python
python:
  - "3.3"
  - "3.4"
  - "pypy3"
install:
  - "pip install -r requirements.txt"
  - "pushd src/basepkg"
  - "pip install ."
script:
  - behave --tags=-@slow features/
  - py.test tests/
