language: python
python:
  - "3.3"
  - "3.4"
  - "pypy3"
install:
  - "pip install -r requirements.txt"
  - "cd src/basepkg && pip install ."
script:
  - py.test src/basepkg/tests
  - cd src/basepkg && behave --tags=-@slow features/
