version: 1
formatters:
  concise:
    format: '%(asctime)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(levelname)s - %(filename)s:%(lineno)3d - %(funcName)s() :: %(message)s'
  thread_info:
    format: '%(asctime)s - %(levelname)s - %(filename)s:%(lineno)3d - %(funcName)s() - %(thread)d:%(threadName)s :: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: concise
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    filename: 'log.log'
    maxBytes: 1000000
    backupCount: 3
    level: INFO
    formatter: detailed
loggers:
  gp_tools:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  gp_tools.fuzzing:
    level: INFO
    handlers: [console, file]
    propagate: no
  gp_tools.fuzzing.FuzzExecutor:
    level: WARNING
    handlers: [console, file]
    propagate: no
root:
  level: WARNING
  handlers: [console]
