version: 1
formatters:
  concise:
    format: 'TEST configuration - %(asctime)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(levelname)s - %(filename)s:%(lineno)3d - %(funcName)s() :: %(message)s'
  thread_info:
    format: '%(asctime)s - %(levelname)s - %(filename)s:%(lineno)3d - %(funcName)s() - %(thread)d:%(threadName)s :: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: concise
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    filename: 'fuzzing.log'
    maxBytes: 100000
    backupCount: 3
    level: DEBUG
    formatter: detailed
loggers:
  fuzzing:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  fuzzing.fuzzing:
    level: INFO
    handlers: [console, file]
    propagate: no
  fuzzing.fuzzing.FuzzExecutor:
    level: INFO
    handlers: [file, console]
    propagate: no
root:
  level: WARNING
  handlers: [console]
